From scratch
MAINTAINER zhangwenlong@loongson.cn
ADD openEuler-24.03.rootfs.loongarch64.tar.gz /
COPY git-lfs-3.6.1-1.oe2403sp1.loongarch64.rpm /
COPY openEuler.repo /etc/yum.repos.d/openEuler.repo
RUN yum install -y /git-lfs-3.6.1-1.oe2403sp1.loongarch64.rpm gdb-gdbserver
RUN git lfs install
RUN sed -i 's|RPM_BUILD_NCPUS="%{getncpus}"|RPM_BUILD_NCPUS="%{expr:%{getncpus} > 32 ? %{getncpus} / 8 : 4}"|' /usr/lib/rpm/macros
CMD ["/bin/bash"]
