From scratch
MAINTAINER zhangwenlong@loongson.cn
ADD openEuler-22.03-LTS.rootfs.loongarch64.tar.gz /
RUN rm -rf /etc/yum.repos.d/openEuler.repo ;\
    repos_baseos_url="http://repo.openeuler.org/openEuler-22.03-LTS/OS/loongarch64/"; \
    yum install --repofrompath=local,$repos_baseos_url --nogpgcheck \
    -y http://10.130.43.27/os-packages/openeuler/openEuler-22.03-LTS/RPMS/loongarch64/git-lfs-3.5.1-1.loongarch64.rpm \
    http://10.130.43.27/os-packages/openeuler/openEuler-22.03-LTS/RPMS/loongarch64/gdb-gdbserver-11.1-16.loongarch64.rpm \
    basesystem bash ca-certificates openEuler-release openEuler-gpg-keys \
    openEuler-repos chkconfig cracklib crypto-policies dnf \
    expat gawk gdbm glib2 gmp gnupg2 gpgme grep ima-evm-utils-libs \
    json-c mpfr ncurses-base procps-ng rpm findutils \
    npth p11-kit p11-kit-trust pcre2 popt readline rootfiles \
    rpm sed setup systemd-libs tzdata vim-minimal xz yum \
    git git-core make gcc procps rpm-build findutils dnf-plugins-core
RUN sed -i 's|RPM_BUILD_NCPUS="%{getncpus}"|RPM_BUILD_NCPUS="%{expr:%{getncpus} > 32 ? %{getncpus} / 8 : 4}"|' /usr/lib/rpm/macros
RUN git lfs install
RUN echo "timeout=120" >> /etc/yum.conf ; echo "minrate=0" >> /etc/yum.conf ; echo "retries=5" >> /etc/yum.conf
CMD ["/bin/bash"]
